<h1><center> PPOL564 - Data Science I: Foundations<br><br><br><br><font color='grey'> Using Numpy </font> </center><h1>

## In this notebook

- Beyond nested lists 
- Basics of using Numpy
- Broadcasting and Vectorization
- From Matrix to Data Frame: Dealing with multiple data types

In [2]:
import numpy as np
import csv
import math
import requests 

Import data used in the notebook. Data will save to the notebook's directory

In [4]:
def download_data(git_loc,dest_name):
    '''
    Downloads data from Github and saves it to the notebook's working directory.
    '''
    req = requests.get(git_loc)
    with open(dest_name,"w") as file:
        for line in req.text:
            file.writelines(line)
download_data('https://raw.githubusercontent.com/edunford/ppol564/master/lectures/lecture_07/gapminder.csv',
         "gapminder.csv")

# Limitations of Nested Lists in DS

As we've seen, we can represent data in Python as **nested lists**. For example, consider the again the Gapminder data.

In [2]:
gap_data = []
with open("gapminder.csv",mode='rt') as file:
    data = csv.reader(file)
    for row in data:
        gap_data.append(row)

# Look at the "head" of the data (first five entries)        
gap_data[:5]

[['country', 'lifeExp', 'gdpPercap'],
 ['Guinea_Bissau', '39.21', '652.157'],
 ['Bolivia', '52.505', '2961.229'],
 ['Austria', '73.103', '20411.916'],
 ['Malawi', '43.352', '575.447']]

One challenge of working with data in this format is how it's **indexed**.

We can easily index each row entry accessing the rows position.

In [3]:
gap_data[3]

['Austria', '73.103', '20411.916']

We can then access a specific ("column") value, but referencing the index position of the second list. 

In [4]:
gap_data[3][1] 

'73.103'

To do this systematically, say by referencing a single variable in the data, we need to use information about both these indices and loop through the values. 

In [5]:
column_names = gap_data[0] # Get the names of the columns
column_names

['country', 'lifeExp', 'gdpPercap']

In [6]:
# Draw out the index for the column 
var_ind = column_names.index("gdpPercap") 
var_ind

2

In [7]:
for row in gap_data:
    print(row[var_ind])

gdpPercap
652.157
2961.229
20411.916
575.447
17473.723
2591.853
5406.038
10888.176
3312.788
2447.909
20556.684
5733.625
65332.91
17262.623
1356.671
810.384
2469.167
9331.712
1741.365
22410.746
1314.38
7208.065
14074.582
7866.872
8416.554
780.553
16245.209
3477.21
1200.416
680.133
3484.779
12013.579
13969.037
1044.582
5613.844
4469.453
4898.398
1854.731
675.368
6384.055
7269.216
1153.82
1569.275
6197.645
3163.352
6703.289
14160.936
4426.026
13920.011
2697.833
17425.382
1488.309
817.559
648.343
6283.259
3675.582
1835.01
3009.288
675.669
10863.164
3255.367
1017.713
542.278
673.093
20261.744
604.814
1335.595
1165.454
11529.865
4768.942
1358.199
7300.17
2844.856
3074.031
1533.122
12138.562
635.858
5031.504
1912.825
802.675
7724.113
1382.782
439.333
27074.334
19380.473
17750.87
4431.847
1057.296
3045.966
18077.664
19980.596
1692.805
782.729
7376.583
2834.413
776.067
10088.516
20531.422
1140.793
471.663
5754.827
5448.611
2174.771
21671.825
1155.395
541.003
19900.758
3759.997
8217.318
509.115


Constantly indexing and looping like this can be _inefficient_. 

numpy arrays are optimized to handle these types of data _matrix_ computations, by 

1. offering a way to efficiently index and slice data
2. vectorizing operations
3. efficiently storing data in memory 

In [8]:
# Convert our gap_data to a numpy array
gap_data_np = np.array(gap_data)
gap_data_np

array([['country', 'lifeExp', 'gdpPercap'],
       ['Guinea_Bissau', '39.21', '652.157'],
       ['Bolivia', '52.505', '2961.229'],
       ['Austria', '73.103', '20411.916'],
       ['Malawi', '43.352', '575.447'],
       ['Finland', '72.992', '17473.723'],
       ['North_Korea', '63.607', '2591.853'],
       ['Malaysia', '64.28', '5406.038'],
       ['Hungary', '69.393', '10888.176'],
       ['Congo', '52.502', '3312.788'],
       ['Morocco', '57.609', '2447.909'],
       ['Germany', '73.444', '20556.684'],
       ['Ecuador', '62.817', '5733.625'],
       ['Kuwait', '68.922', '65332.91'],
       ['New_Zealand', '73.989', '17262.623'],
       ['Mauritania', '52.302', '1356.671'],
       ['Uganda', '47.619', '810.384'],
       ['Equatorial Guinea', '42.96', '2469.167'],
       ['Croatia', '70.056', '9331.712'],
       ['Indonesia', '54.336', '1741.365'],
       ['Canada', '74.903', '22410.746'],
       ['Comoros', '52.382', '1314.38'],
       ['Montenegro', '70.299', '7208.065'],
      

In [9]:
gap_data_np[:,2]

array(['gdpPercap', '652.157', '2961.229', '20411.916', '575.447',
       '17473.723', '2591.853', '5406.038', '10888.176', '3312.788',
       '2447.909', '20556.684', '5733.625', '65332.91', '17262.623',
       '1356.671', '810.384', '2469.167', '9331.712', '1741.365',
       '22410.746', '1314.38', '7208.065', '14074.582', '7866.872',
       '8416.554', '780.553', '16245.209', '3477.21', '1200.416',
       '680.133', '3484.779', '12013.579', '13969.037', '1044.582',
       '5613.844', '4469.453', '4898.398', '1854.731', '675.368',
       '6384.055', '7269.216', '1153.82', '1569.275', '6197.645',
       '3163.352', '6703.289', '14160.936', '4426.026', '13920.011',
       '2697.833', '17425.382', '1488.309', '817.559', '648.343',
       '6283.259', '3675.582', '1835.01', '3009.288', '675.669',
       '10863.164', '3255.367', '1017.713', '542.278', '673.093',
       '20261.744', '604.814', '1335.595', '1165.454', '11529.865',
       '4768.942', '1358.199', '7300.17', '2844.856', '3074.0

Let's time those two operations: as we can see, the boost in performance (and the conceptual ease of execution) is huge.

In [10]:
%%timeit
for row in gap_data:
    row[var_ind]

6.94 µs ± 47.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%%timeit
gap_data_np[:,2]

309 ns ± 2.92 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Basics of Using Numpy

## Vectors, Matrices, and N-Dimensional Arrays

In [12]:
# vector as a list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [13]:
# A matrix is a nested list
M = np.array([[1,2,3,4],
             [2,3,4,1],
             [-1,1,2,1]])
print(M)
M.shape

[[ 1  2  3  4]
 [ 2  3  4  1]
 [-1  1  2  1]]


(3, 4)

In [14]:
#  An ndimensional array is a nested list
A = np.array([
              [
                [1,2,3,4],
                [2,3,4,1],
                [-1,1,2,1]
              ],
             [
                 [1,2,3,4],
                 [2,3,4,1],
                 [-1,1,2,1]]
              ])
print(A)
A.shape

[[[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]

 [[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]]


(2, 3, 4)

## Generating Arrays

### `np.arange`
Generate a range of numbers by some interval
```python
np.arange(start,stop,by)
```

In [15]:
np.arange(1, 10, .5 )

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [3]:
np.arange(0,1+.01,.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

### `np.linspace`

Generate a a vector of length N where each entry is evenly spaced between the interval for the number requested.
```
np.linspace(start,end,length)
```

In [17]:
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.linspace(0,1,3) 

array([0. , 0.5, 1. ])

### Random Number Generation `np.random.`

We'll use the `.random.` sub-library in numpy to generate numerical numpy arrays from known random distributions. 

Whenever we randomly generate numbers, we normally want to replicate our results. To do so, we need to set a `seed` that ensures we'll generate the same random numbers again. 

In [19]:
np.random.seed(123)

Generate random numbers from a standard normal distribution. 

In [20]:
np.random.randn(10) 

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

Generate an array of random integers within a range: `np.random.randint(start,end,n)`

In [21]:
np.random.randint(1,10,10)

array([4, 5, 1, 1, 5, 2, 8, 4, 3, 5])

Also, we can generate random values from **known distributions**, e.g.

- Normal (Gaussian) 
- Binomial (or Bernoulli "a.k.a. the coin flip distribution"when there are only two outcomes)
- Poisson

In [22]:
np.random.binomial(1,.5,10) # coin flip distribution

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [23]:
np.random.normal(5,1,10) # normal (continuous) distribution

array([5.9071052 , 3.5713193 , 4.85993128, 4.1382451 , 4.74438063,
       2.20141089, 3.2284669 , 4.30012277, 5.92746243, 4.82636432])

In [24]:
np.random.poisson(1,10) # count distribution

array([2, 0, 0, 1, 0, 2, 1, 2, 0, 0])

In [25]:
np.random.uniform(1,5,10) # uniform distribution

array([2.66808884, 3.72520306, 4.50182737, 3.04168935, 3.67725513,
       3.34374621, 3.49961401, 3.6987562 , 4.36936975, 1.33277995])

We'll delve more into random number generation later in the semester.

## Generating Matrices (2-dimensional Arrays)

In [26]:
# Matrix full of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# Matrix full of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# empty container
empty_array = np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

Generating a matrix similar to the one you already have

In [5]:
X = np.zeros((4,4))
np.ones_like(X)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros_like(P)

## Reshaping Arrays

In [6]:
# Call the shape of an array
v = np.random.randint(1,100,30)
v

array([41, 28,  3, 55, 35, 43,  1, 77,  5, 95, 12, 69, 60,  1, 94, 76, 58,
       70, 57, 73, 82,  6, 27, 48, 66, 73, 32, 17, 72, 23])

In [7]:
v.reshape(5,6)

array([[41, 28,  3, 55, 35, 43],
       [ 1, 77,  5, 95, 12, 69],
       [60,  1, 94, 76, 58, 70],
       [57, 73, 82,  6, 27, 48],
       [66, 73, 32, 17, 72, 23]])

In [8]:
v.reshape(10,3)

array([[41, 28,  3],
       [55, 35, 43],
       [ 1, 77,  5],
       [95, 12, 69],
       [60,  1, 94],
       [76, 58, 70],
       [57, 73, 82],
       [ 6, 27, 48],
       [66, 73, 32],
       [17, 72, 23]])

Can only reshape given the appropriate dimensions

In [9]:
v.reshape(10,2)

ValueError: cannot reshape array of size 30 into shape (10,2)

In [10]:
# use negative 1 to guess the dimension
P = np.random.randn(20).reshape(10,-1)
P.shape

(10, 2)

In [11]:
P

array([[-1.48635895e+00, -9.58685682e-01],
       [-1.24432742e+00,  3.14553808e-01],
       [-4.43642384e-01, -4.53963597e-01],
       [ 1.43936170e-01,  6.36996117e-01],
       [-1.47723150e+00,  4.55764472e-01],
       [-4.59038465e-01, -1.99879197e-01],
       [ 4.29367339e-01,  2.05851218e+00],
       [-2.13301257e-01,  9.14560780e-04],
       [ 6.10234542e-01, -9.69664937e-02],
       [-1.23060054e+00, -3.15366792e-01]])

In [12]:
# Alternative way to change the shape
P.shape = 2,10
P.shape

(2, 10)

In [13]:
P

array([[-1.48635895e+00, -9.58685682e-01, -1.24432742e+00,
         3.14553808e-01, -4.43642384e-01, -4.53963597e-01,
         1.43936170e-01,  6.36996117e-01, -1.47723150e+00,
         4.55764472e-01],
       [-4.59038465e-01, -1.99879197e-01,  4.29367339e-01,
         2.05851218e+00, -2.13301257e-01,  9.14560780e-04,
         6.10234542e-01, -9.69664937e-02, -1.23060054e+00,
        -3.15366792e-01]])

## Indexing and Slicing

```
M[row,column]
```

In [14]:
X = np.linspace(1,25,25).reshape(5,5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [15]:
X[0] # index first row 

array([1., 2., 3., 4., 5.])

In [16]:
X[:,0] # index first column

array([ 1.,  6., 11., 16., 21.])

In [17]:
X[0,0] # index a specific cell 

1.0

In [ ]:
# Can use : or ... for a complete subsection
print(X[:,1])
print(X[...,1])

In [18]:
# slice rows and columns
X[0:3,0:3] 

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]])

In [19]:
X[-1,:] # last row

array([21., 22., 23., 24., 25.])

In [20]:
X[:,-1] # last column

array([ 5., 10., 15., 20., 25.])

Demand specific indices in requested order.

In [21]:
X[[3,0,2],:]

array([[16., 17., 18., 19., 20.],
       [ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.]])

In [22]:
X[:,[3,0,2]]

array([[ 4.,  1.,  3.],
       [ 9.,  6.,  8.],
       [14., 11., 13.],
       [19., 16., 18.],
       [24., 21., 23.]])

## Boolean Arrays

We can use vectorization (see below) to great effect with boolean (logical) evaluations. This offers a way to quickly and easily subset data by particular conditions

In [23]:
D = np.random.randint(1,100,50).reshape(10,5)
D

array([[19, 88, 70,  1, 55],
       [24, 54, 92, 52, 56],
       [97, 35,  5, 70, 40],
       [66,  5, 46, 81, 79],
       [35, 13, 12, 37, 42],
       [18, 85, 59, 51, 25],
       [35, 75, 99, 51, 32],
       [14, 39, 78, 19, 43],
       [88, 17, 99, 47, 77],
       [59,  3, 57, 83, 45]])

In [24]:
D >= 50

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True, False, False,  True, False],
       [ True, False, False,  True,  True],
       [False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True, False,  True],
       [ True, False,  True,  True, False]])

In [25]:
D[D >= 50]

array([88, 70, 55, 54, 92, 52, 56, 97, 70, 66, 81, 79, 85, 59, 51, 75, 99,
       51, 78, 88, 99, 77, 59, 57, 83])

In [26]:
D[D >= 50] = -999
D

array([[  19, -999, -999,    1, -999],
       [  24, -999, -999, -999, -999],
       [-999,   35,    5, -999,   40],
       [-999,    5,   46, -999, -999],
       [  35,   13,   12,   37,   42],
       [  18, -999, -999, -999,   25],
       [  35, -999, -999, -999,   32],
       [  14,   39, -999,   19,   43],
       [-999,   17, -999,   47, -999],
       [-999,    3, -999, -999,   45]])

## Reassignment

In [27]:
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [28]:
X[:3,:3] = 0
X

array([[ 0.,  0.,  0.,  4.,  5.],
       [ 0.,  0.,  0.,  9., 10.],
       [ 0.,  0.,  0., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [29]:
X[1,2] = -999
X[4,4] = -999

In [30]:
X

array([[   0.,    0.,    0.,    4.,    5.],
       [   0.,    0., -999.,    9.,   10.],
       [   0.,    0.,    0.,   14.,   15.],
       [  16.,   17.,   18.,   19.,   20.],
       [  21.,   22.,   23.,   24., -999.]])

In [31]:
D = np.random.randint(1,100,50).reshape(10,5)
D[D <= 50] = 1
D[D > 50] = 0
D

array([[1, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

#### If-else with `np.where()`

Similar to `R`'s `ifelse()`

In [32]:
D = np.random.randint(1,100,50).reshape(10,5)
D

array([[49,  7, 46, 35, 85],
       [ 4, 30, 16, 69, 77],
       [19, 60, 52,  2, 74],
       [61, 95, 25, 28,  2],
       [69, 26,  5, 63, 94],
       [15, 29, 78, 31, 76],
       [ 5, 74, 88, 27, 46],
       [ 6, 19, 26, 87, 44],
       [79, 65, 78, 24, 48],
       [83, 86, 40, 22, 36]])

In [33]:
np.where(D>50,0,1)

array([[1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 1]])

#### Reassignment with Compound Boolean Statements

In [34]:
b = np.random.randint(1,10,100)
b

array([3, 8, 2, 3, 1, 7, 8, 8, 3, 4, 8, 3, 2, 7, 2, 2, 1, 5, 2, 2, 3, 3,
       5, 7, 3, 4, 9, 4, 6, 6, 2, 6, 1, 7, 2, 6, 3, 8, 4, 2, 8, 7, 3, 3,
       6, 2, 7, 5, 7, 3, 8, 2, 2, 7, 3, 4, 9, 7, 8, 2, 6, 3, 6, 5, 3, 8,
       7, 8, 3, 7, 1, 7, 9, 6, 3, 8, 2, 4, 4, 6, 9, 6, 2, 7, 1, 1, 6, 2,
       5, 9, 9, 6, 7, 9, 6, 7, 3, 1, 9, 7])

In [35]:
b[(b < 8) & (b > 4)]

array([7, 7, 5, 5, 7, 6, 6, 6, 7, 6, 7, 6, 7, 5, 7, 7, 7, 6, 6, 5, 7, 7,
       7, 6, 6, 6, 7, 6, 5, 6, 7, 6, 7, 7])

In [ ]:
b[(b < 8) & (b > 4)] = -999
b

## Stacking

We can easily stack and grow numpy arrays

In [36]:
m1 = np.random.randn(10).reshape(5,-1).round(1)
m2 = np.random.poisson(1,10).reshape(5,-1)

In [37]:
m1

array([[-0.8,  1.5],
       [-0.5,  0.7],
       [ 1.7, -0.5],
       [ 1.7, -2.2],
       [ 0.5, -0.8]])

In [38]:
m2

array([[1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2]])

#### `rbind`: binding row

In [39]:
# stack the two columns using concatenate
np.concatenate([m1,m2],axis=0)

array([[-0.8,  1.5],
       [-0.5,  0.7],
       [ 1.7, -0.5],
       [ 1.7, -2.2],
       [ 0.5, -0.8],
       [ 1. ,  0. ],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 1. ,  1. ],
       [ 2. ,  2. ]])

In [40]:
# or use verticle stack
np.vstack([m1,m2])

array([[-0.8,  1.5],
       [-0.5,  0.7],
       [ 1.7, -0.5],
       [ 1.7, -2.2],
       [ 0.5, -0.8],
       [ 1. ,  0. ],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 1. ,  1. ],
       [ 2. ,  2. ]])

#### `cbind`: binding columns

In [41]:
np.concatenate([m1,m2],axis=1)

array([[-0.8,  1.5,  1. ,  0. ],
       [-0.5,  0.7,  1. ,  1. ],
       [ 1.7, -0.5,  0. ,  0. ],
       [ 1.7, -2.2,  1. ,  1. ],
       [ 0.5, -0.8,  2. ,  2. ]])

In [42]:
np.hstack([m1,m2])

array([[-0.8,  1.5,  1. ,  0. ],
       [-0.5,  0.7,  1. ,  1. ],
       [ 1.7, -0.5,  0. ,  0. ],
       [ 1.7, -2.2,  1. ,  1. ],
       [ 0.5, -0.8,  2. ,  2. ]])

## Views vs. Copies

Note that when we slice an array we **_do not copy the array_**, rather we get a "**view**" of the array. 

In [33]:
# Recall the behavior of double assignment with lists
x = [1,2,3]
y = x
y[2] = 100
x

[1, 2, 100]

In [34]:
# We can get around this behavior by making copies. 
# One way to make a copy is to slice
y = x[:]
y[2] = -999
x

[1, 2, 100]

When we slice an array, we get a sub-"view" of the data that still effects the original data object.

In [35]:
P = np.ones((5,5))
P

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
g = P[:2,:2] 
g

array([[1., 1.],
       [1., 1.]])

In [37]:
g += 100
g

array([[101., 101.],
       [101., 101.]])

In [38]:
P

array([[101., 101.,   1.,   1.,   1.],
       [101., 101.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

As [noted in the reading](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html): 

> "This **_default behavior is actually quite useful_**: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer."

To get around this behavior, we again just need to make a `.copy()`. 

In [39]:
g2 = P[:2,:2].copy()
g2 -= 1000
g2

array([[-899., -899.],
       [-899., -899.]])

In [40]:
P

array([[101., 101.,   1.,   1.,   1.],
       [101., 101.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

# Broadcasting 

**Broadcasting** makes it possible for operations to be performed on arrays of mismatched shapes.

Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes.

For example, say we have a numpy array of dimensions (5,1)

$$ 
\begin{bmatrix} 1\\2\\3\\4\\5\end{bmatrix}
$$

Now say we wanted to add the values in this array by 5

$$ 
\begin{bmatrix} 1\\2\\3\\4\\5\end{bmatrix} + 5
$$

Broadcasting "pads" the array of 5 (which is shape = 1,1), and extends it so that it has similar dimension to the larger array in which the computation is being performed.

$$ 
\begin{bmatrix} 1\\2\\3\\4\\5\end{bmatrix} + \begin{bmatrix} 5\\\color{lightgrey}{5}\\\color{lightgrey}{5}\\\color{lightgrey}{5}\\\color{lightgrey}{5}\end{bmatrix}
$$

$$ 
\begin{bmatrix} 1 + 5\\2 + 5\\3 + 5\\4 + 5\\5 + 5\end{bmatrix} 
$$

$$ 
\begin{bmatrix} 6\\7\\8\\9\\10\end{bmatrix} 
$$

In [41]:
A = np.array([1,2,3,4,5])
A + 5

array([ 6,  7,  8,  9, 10])

By 'broadcast', we mean that the smaller array is made to match the size of the larger array in order to allow for element-wise manipulations.

### How it works:

- Shapes of the two arrays are compared _element-wise_. 
- Dimensions are considered in reverse order, starting with the trailing dimensions, and working forward 
- We are stretching the smaller array by making copies of its elements. However, and this is key, no actual copies are made, making the method computationally and memory efficient.

A general **Rule of thumb**: All corresponding dimension of the arrays must be compatible or one of the two dimensions is 1.

## Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays (from [reading](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)):


### Rule 1
> If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

### Rule 2

> If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

### Rule 3 

> If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

#### Example 1

In [42]:
np.arange(3) + 5

array([5, 6, 7])

$$
\texttt{np.arange(3)} = \begin{bmatrix} 0&1&2\end{bmatrix}
$$

<br> 

$$
\texttt{5}  = \begin{bmatrix} 5 \end{bmatrix}
$$

<br> 

$$
\begin{bmatrix} 0&1&2\end{bmatrix} + \begin{bmatrix} 5 & \color{lightgrey}{5} & \color{lightgrey}{5}\end{bmatrix} = \begin{bmatrix} 5 & 6 & 7\end{bmatrix} 
$$

#### Example 2

In [43]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

$$
\texttt{np.ones((3,3)) = }\begin{bmatrix} 1 & 1 & 1\\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix}
$$

<br>

$$
\texttt{np.arange(3)} = \begin{bmatrix} 0 & 1 & 2\end{bmatrix} 
$$

<br>

$$
\begin{bmatrix} 1 & 1 & 1\\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix} + 
\begin{bmatrix} 0 & 1 & 2\\ \color{lightgrey}{0} & \color{lightgrey}{1} & \color{lightgrey}{2} \\  \color{lightgrey}{0} & \color{lightgrey}{1} & \color{lightgrey}{2}\end{bmatrix}  = 
\begin{bmatrix} 1 & 2 & 3\\ 1 & 2 & 3 \\ 1 & 2 & 3 \end{bmatrix} 
$$

#### Example 3

In [44]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

$$
\texttt{np.arange(3).reshape(3,1)} = \begin{bmatrix} 0 \\ 1 \\ 2\end{bmatrix} 
$$

<br>

$$
\texttt{np.arange(3)} = \begin{bmatrix} 0 & 1 & 2\end{bmatrix} 
$$

<br>

$$
\begin{bmatrix} 0 & \color{lightgrey}{0} & \color{lightgrey}{0} \\ 1 & \color{lightgrey}{1} & \color{lightgrey}{1} \\  2 & \color{lightgrey}{2} & \color{lightgrey}{2}\end{bmatrix} +
\begin{bmatrix} 0 & 1 & 2\\ \color{lightgrey}{0} & \color{lightgrey}{1} & \color{lightgrey}{2} \\  \color{lightgrey}{0} & \color{lightgrey}{1} & \color{lightgrey}{2}\end{bmatrix}  =
\begin{bmatrix} 0 & 1 & 2\\ 1 &2&3 \\ 2& 3 & 4\end{bmatrix} 
$$


#### Example 4

Example of dimensional disagreement.

In [45]:
np.ones((4,7)) 

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.ones((4,7))  + np.zeros( (5,9) )

ValueError: operands could not be broadcast together with shapes (4,7) (5,9) 

In [ ]:
np.ones((4,7))  + np.zeros( (1,7) )

# Vectorization

Similar to broadcasting, vectorization allows for simultaneous computation along all values in the array. 

In [47]:
X = np.random.randint(1,10,50).reshape(10,5)
X

array([[7, 4, 7, 7, 7],
       [2, 4, 5, 4, 2],
       [1, 6, 9, 7, 9],
       [2, 1, 4, 2, 4],
       [5, 8, 7, 2, 5],
       [4, 4, 8, 7, 9],
       [7, 5, 5, 8, 1],
       [1, 9, 9, 5, 9],
       [7, 2, 7, 9, 8],
       [2, 8, 2, 8, 9]])

In [48]:
np.log(X)

array([[1.94591015, 1.38629436, 1.94591015, 1.94591015, 1.94591015],
       [0.69314718, 1.38629436, 1.60943791, 1.38629436, 0.69314718],
       [0.        , 1.79175947, 2.19722458, 1.94591015, 2.19722458],
       [0.69314718, 0.        , 1.38629436, 0.69314718, 1.38629436],
       [1.60943791, 2.07944154, 1.94591015, 0.69314718, 1.60943791],
       [1.38629436, 1.38629436, 2.07944154, 1.94591015, 2.19722458],
       [1.94591015, 1.60943791, 1.60943791, 2.07944154, 0.        ],
       [0.        , 2.19722458, 2.19722458, 1.60943791, 2.19722458],
       [1.94591015, 0.69314718, 1.94591015, 2.19722458, 2.07944154],
       [0.69314718, 2.07944154, 0.69314718, 2.07944154, 2.19722458]])

The computations are performed on each element in the array _simultaneously_.

Again, let's consider what this same operation would need to look like if we were dealing with a nested list. We'd need to perform each operation element-by-element in the nested list structure. 

In [49]:
X2 = X.tolist()
n_rows = len(X2)
n_cols = len(X2[0])
for i in range(n_rows):
    for j in range(n_cols):
        X2[i][j] = math.log(X2[i][j])
X2

[[1.9459101490553132,
  1.3862943611198906,
  1.9459101490553132,
  1.9459101490553132,
  1.9459101490553132],
 [0.6931471805599453,
  1.3862943611198906,
  1.6094379124341003,
  1.3862943611198906,
  0.6931471805599453],
 [0.0,
  1.791759469228055,
  2.1972245773362196,
  1.9459101490553132,
  2.1972245773362196],
 [0.6931471805599453,
  0.0,
  1.3862943611198906,
  0.6931471805599453,
  1.3862943611198906],
 [1.6094379124341003,
  2.0794415416798357,
  1.9459101490553132,
  0.6931471805599453,
  1.6094379124341003],
 [1.3862943611198906,
  1.3862943611198906,
  2.0794415416798357,
  1.9459101490553132,
  2.1972245773362196],
 [1.9459101490553132,
  1.6094379124341003,
  1.6094379124341003,
  2.0794415416798357,
  0.0],
 [0.0,
  2.1972245773362196,
  2.1972245773362196,
  1.6094379124341003,
  2.1972245773362196],
 [1.9459101490553132,
  0.6931471805599453,
  1.9459101490553132,
  2.1972245773362196,
  2.0794415416798357],
 [0.6931471805599453,
  2.0794415416798357,
  0.69314718055994

Vectorization frees us from this tedium. Moreover, it's extremely efficient so we can perform computations quickly.

For example:

In [50]:
# Locate the absolute value for an array
np.abs([1,2,-6,7,8])

array([1, 2, 6, 7, 8])

In [51]:
# Round Values to the k-th decimal point
np.round(np.log(X),1)

array([[1.9, 1.4, 1.9, 1.9, 1.9],
       [0.7, 1.4, 1.6, 1.4, 0.7],
       [0. , 1.8, 2.2, 1.9, 2.2],
       [0.7, 0. , 1.4, 0.7, 1.4],
       [1.6, 2.1, 1.9, 0.7, 1.6],
       [1.4, 1.4, 2.1, 1.9, 2.2],
       [1.9, 1.6, 1.6, 2.1, 0. ],
       [0. , 2.2, 2.2, 1.6, 2.2],
       [1.9, 0.7, 1.9, 2.2, 2.1],
       [0.7, 2.1, 0.7, 2.1, 2.2]])

In [52]:
# Count the number of non zeros
np.count_nonzero(np.array([1,0,8,0,1]))

3

Numpy comes baked in with a large number of `ufuncs` (or "universal functions") that are all vectorized. [See here for a detailed list of these operations.](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

## Vectorization across array dimensions

The universal functions constructed in Python come with an `axis` argument that outlines how the function should be applied

In [53]:
A = np.random.randint(1,10,100).reshape(20,5)
A

array([[8, 2, 4, 2, 9],
       [8, 6, 2, 3, 6],
       [3, 3, 4, 3, 7],
       [8, 2, 4, 9, 4],
       [8, 4, 4, 6, 7],
       [1, 9, 8, 8, 5],
       [5, 6, 1, 9, 3],
       [6, 2, 6, 3, 5],
       [4, 1, 4, 8, 8],
       [3, 6, 2, 8, 6],
       [2, 3, 9, 6, 1],
       [4, 4, 4, 2, 8],
       [7, 4, 2, 8, 3],
       [7, 6, 9, 5, 8],
       [9, 6, 3, 5, 4],
       [4, 2, 8, 9, 6],
       [8, 8, 8, 6, 1],
       [1, 9, 2, 1, 5],
       [6, 5, 6, 1, 8],
       [2, 3, 3, 8, 8]])

Consider calculating the average across some data set. By default, the ufunc `.mean()` will calculate the average for the entire data matrix.

In [54]:
A.mean()

5.1

If we wanted to calculate the mean for each observation (row) or variable (column), we'll need to use the `axis` argument to specify which. 

- `axis = 0` == move across the columns
- `axis = 1` == move across the rows

In [55]:
A.mean(axis=0)

array([5.2 , 4.55, 4.65, 5.5 , 5.6 ])

In [56]:
A.mean(axis=1)

array([5. , 5. , 4. , 5.4, 5.8, 6.2, 4.8, 4.4, 5. , 5. , 4.2, 4.4, 4.8,
       7. , 5.4, 5.8, 6.2, 3.6, 5.2, 4.8])

## Building vectorized functions

Consider the following function that yields a different string when input `a` is larger/smaller than input `b`.

In [57]:
def bigsmall(a,b):
    if a > b:
        return "A is larger"
    else:
        return "B is larger"

In [58]:
bigsmall(5,6)

'B is larger'

In [59]:
bigsmall(6,5)

'A is larger'

We can implement this function in a vectorized fashion using the `np.vectorize()` method. 

In [60]:
# Create a vectorized version of the function
vec_bigsmall = np.vectorize(bigsmall)
vec_bigsmall 

In [61]:
# And now implement on arrays of numbers!
vec_bigsmall([0,2,5,7,0],[4,3,10,2,6])

array(['B is larger', 'B is larger', 'B is larger', 'A is larger',
       'B is larger'], dtype='<U11')

# Road to the DataFrame &rarr; Handling Multiple Data Types

Out of the box, numpy arrays can only handle one data class at a time...

In [62]:
x = np.array([1,2,3,4])
x.dtype                # examine the data type contained within 

dtype('int64')

And we can't necessarily change the data type on the fly by ducktyping (i.e. overwriting the data object with different types of values).

In [63]:
x[1] = .04
x   

array([1, 0, 3, 4])

In [64]:
x[1] = "this"
x

ValueError: invalid literal for int() with base 10: 'this'

To do this, we need to alter the data type of the data contained within the array with `.astype()`

In [65]:
x.astype('f')

array([1., 0., 3., 4.], dtype=float32)

In [66]:
x.astype('U')

array(['1', '0', '3', '4'], dtype='<U21')

List of all data types and their conversions ([table drawn from reading](https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html))

| Character | Description	 | Example  |
|:-------:|:------------:|:--------:|
| `b` | Byte | `np.dtype('b')` |
| `i` | Signed integer | `np.dtype('i4') == np.int32`
| `u` | Unsigned integer | `np.dtype('u1') == np.uint8`
| `f` | Floating point | `np.dtype('f8') == np.int64`
| `c` | Complex floating point | `np.dtype('c16') == np.complex128`
| `S`, `a` | String | `np.dtype('S5')`
| `U` | Unicode string | `np.dtype('U') == np.str_`
| `V` | Raw data (void) | `np.dtype('V') == np.void`

This limitation extends itself to heterogeneous data types

In [67]:
nested_list = [['a','b','c'],[1,2,3],[.3,.55,1.2]]
nested_list

[['a', 'b', 'c'], [1, 2, 3], [0.3, 0.55, 1.2]]

In [68]:
data = np.array(nested_list).T
data

array([['a', '1', '0.3'],
       ['b', '2', '0.55'],
       ['c', '3', '1.2']], dtype='<U4')

All the data in the matrix is treated as a string!

### Structured Arrays
To get around this, we need to again be explicit about the data type of each column. Here we pre-specify a data table and it's inputs.

In [69]:
data = np.zeros((3), dtype={'names':('v1', 'v2', 'v3'),
                            'formats':('U5', 'i', 'f')})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('v1', '<U5'), ('v2', '<i4'), ('v3', '<f4')])

We then load the data to the specified columns.

In [70]:
data['v1'] = ['a','b','c']
data['v2'] = [1,2,3]
data['v3'] = [.3,.55,1.2]
data

array([('a', 1, 0.3 ), ('b', 2, 0.55), ('c', 3, 1.2 )],
      dtype=[('v1', '<U5'), ('v2', '<i4'), ('v3', '<f4')])

We can then index, but will do so differently than we observed above. 

In [71]:
data['v1']

array(['a', 'b', 'c'], dtype='<U5')

In [72]:
data[1][['v1','v2']]

('b', 2)

Though possible to deal with heterogeneous data frames using numpy, there is a lot of overhead to constructing a data object. As such, we'll use Pandas series and DataFrames to deal with heterogeneous data. 

# Miscellaneous

### Printing Numpy Arrays

np automatically truncates the data when printing. Handy when you have _alot_ of data

In [73]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [74]:
# We can adjust these settings
np.set_printoptions(threshold=None)
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Missing Values

Numpy provides a data class for missing values (i.e. `nan` == "Not a Number", see [here](https://en.wikipedia.org/wiki/NaN))

In [75]:
Y = np.random.randint(1,10,25).reshape(5,5) + .0
Y

array([[4., 7., 2., 9., 5.],
       [2., 7., 6., 1., 4.],
       [2., 4., 8., 8., 8.],
       [6., 4., 7., 4., 6.],
       [2., 6., 2., 4., 2.]])

In [76]:
Y[Y > 5] = np.nan
Y

array([[ 4., nan,  2., nan,  5.],
       [ 2., nan, nan,  1.,  4.],
       [ 2.,  4., nan, nan, nan],
       [nan,  4., nan,  4., nan],
       [ 2., nan,  2.,  4.,  2.]])

In [77]:
type(np.nan)

float

In [78]:
# scan for missing values
np.isnan(Y)

array([[False,  True, False,  True, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False,  True, False, False, False]])

In [79]:
~np.isnan(Y) # are not NAs

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True, False,  True, False],
       [ True, False,  True,  True,  True]])

When we have missing values, we'll run into issues when computing across the data matrix.

In [80]:
np.mean(Y)

nan

To get around this, we need to use special version of the methods that compensate for the existence of `nan`.

In [81]:
np.nanmean(Y)

3.0

In [82]:
np.nanmean(Y,axis=0)

array([2.5       , 4.        , 2.        , 3.        , 3.66666667])

In [83]:
# Mean impute the missing values
Y[np.where(np.isnan(Y))] = np.nanmean(Y)
Y

array([[4., 3., 2., 3., 5.],
       [2., 3., 3., 1., 4.],
       [2., 4., 3., 3., 3.],
       [3., 4., 3., 4., 3.],
       [2., 3., 2., 4., 2.]])